"""Which generator parts make up every fighter in the game.

Each entry lists catalogue ids in no particular order; the builder sorts the
resulting layers by the z position the LPC project assigns them, so a shield
ends up behind a torso and a helmet in front of a head without special cases.

`attack` picks the animation row used when the fighter swings, shoots or
casts. `body` picks which body type variant of every part gets pulled.

Heroes list three `tiers` instead of one kit: what they set out in, what they
look like once decent gear turns up, and what they look like carrying the best
the shaft has given them.
"""

HEROES = {
    "warden": {
        "body": "male",
        "facing": "right",
        "attack": "slash",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "hair-Plain_dark_brown",
                "legs-Pants_brown",
                "clothes-Longsleeve_brown",
                "shoes-Boots_brown",
                "shield-Shield_round_brown",
                "weapon-Arming_Sword_iron",
            ],
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "legs-Armour_steel",
                "armour-Plate_steel",
                "arms-Armour_steel",
                "shoulders-Plate_steel",
                "shoes-Boots_charcoal",
                "shoes_plate-Boots_Metal_Plating_steel",
                "hat-Greathelm_steel",
                "shield-Heater_Shield_Base_umber",
                "weapon-Longsword_longsword",
            ],
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "legs-Armour_gold",
                "armour-Plate_gold",
                "arms-Armour_gold",
                "shoulders-Plate_gold",
                "shoes-Boots_charcoal",
                "shoes_plate-Boots_Metal_Plating_gold",
                "hat-Greathelm_gold",
                "cape-Solid_maroon",
                "shield-Heater_Shield_Base_coffee",
                "weapon-Longsword_alt_longsword_alt",
            ],
        ],
    },
    "ranger": {
        "body": "female",
        "facing": "right",
        "attack": "shoot",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_dark_brown",
                "legs-Leggings_brown",
                "clothes-Shortsleeve_brown",
                "shoes-Boots_brown",
                "weapon-Normal_light",
                "ammo-Ammo_arrow",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_dark_brown",
                "legs-Leggings_leather",
                "clothes-Longsleeve_forest",
                "shoes-Boots_brown",
                "bauldron-Bauldron_leather",
                "quiver-Quiver_quiver",
                "weapon-Normal_dark",
                "ammo-Ammo_arrow",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_dark_brown",
                "legs-Leggings_leather",
                "clothes-Longsleeve_forest",
                "shoes-Boots_black",
                "bauldron-Bauldron_leather",
                "quiver-Quiver_quiver",
                "cape-Solid_forest",
                "hat-Hood_forest",
                "weapon-Recurve_gold",
                "ammo-Ammo_arrow",
            ],
        ],
    },
    "magus": {
        "body": "female",
        "facing": "right",
        "attack": "cast",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Messy1_dark_brown",
                "clothes-Robe_brown",
                "shoes-Boots_brown",
                "weapon-Simple_staff_simple",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "clothes-Robe_blue",
                "shoes-Boots_charcoal",
                "hat-Hood_blue",
                "weapon-Diamond_staff_silver",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "clothes-Robe_purple",
                "shoes-Boots_black",
                "hat-Hood_purple",
                "cape-Solid_lavender",
                "weapon-Diamond_staff_gold",
            ],
        ],
    },
    "preacher": {
        "body": "male",
        "facing": "right",
        "attack": "slash",
        "extra_anims": {"cast": "cast"},
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "hair-Plain_ash",
                "legs-Pants_gray",
                "clothes-Longsleeve_white",
                "shoes-Boots_brown",
                "weapon-Club_club",
            ],
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "legs-Pants_gray",
                "chainmail-Chainmail_gray",
                "shoes-Boots_brown",
                "hat-Hood_white",
                "cape-Solid_gray",
                "shield-Shield_round_silver",
                "weapon-Mace_mace",
            ],
            [
                "body-Body_color_light",
                "head-Human_male_light",
                "legs-Armour_silver",
                "armour-Plate_silver",
                "arms-Armour_silver",
                "shoulders-Plate_silver",
                "shoes-Boots_charcoal",
                "hat-Close_helm_silver",
                "cape-Solid_white",
                "shield-Shield_round_gold",
                "weapon-Mace_mace",
            ],
        ],
    },
    "cutpurse": {
        "body": "female",
        "facing": "right",
        "attack": "slash",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_black",
                "legs-Leggings_charcoal",
                "clothes-Shortsleeve_charcoal",
                "shoes-Boots_black",
                "weapon-Dagger_dagger",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_black",
                "legs-Leggings_black",
                "clothes-Longsleeve_charcoal",
                "shoes-Boots_black",
                "hat-Hood_black",
                "bauldron-Bauldron_charcoal",
                "weapon-Dagger_dagger",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Ponytail_black",
                "legs-Leggings_black",
                "clothes-Longsleeve_black",
                "shoes-Boots_black",
                "hat-Hood_black",
                "bauldron-Bauldron_charcoal",
                "cape-Solid_black",
                "weapon-Rapier_rapier",
            ],
        ],
    },
    # The three who join later. Each one does something none of the first five
    # can: put somebody back on their feet, hit everything at a cost, or take
    # the speed out of a room.
    "sentinel": {
        "body": "female",
        "facing": "right",
        "attack": "thrust",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Braid_ash",
                "legs-Pants_brown",
                "clothes-Longsleeve_bluegray",
                "shoes-Boots_brown",
                "weapon-Spear_medium",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Braid_ash",
                "legs-Armour_iron",
                "armour-Leather_leather",
                "arms-Armour_iron",
                "shoulders-Plate_iron",
                "shoes-Boots_charcoal",
                "weapon-Halberd_halberd",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "legs-Armour_steel",
                "armour-Plate_steel",
                "arms-Armour_steel",
                "shoulders-Plate_steel",
                "shoes-Boots_charcoal",
                "shoes_plate-Boots_Metal_Plating_steel",
                "hat-Close_helm_steel",
                "cape-Solid_bluegray",
                "weapon-Trident_bronze",
            ],
        ],
    },
    "zealot": {
        "body": "female",
        "facing": "right",
        "attack": "slash",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Shoulderl_ash",
                "legs-Pants_brown",
                "clothes-Robe_brown",
                "shoes-Boots_brown",
                "weapon-Flail_flail",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "legs-Pants_charcoal",
                "clothes-Robe_black",
                "hat-Hood_hood_brown",
                "neck-Scarf_brown",
                "shoes-Boots_black",
                "weapon-Flail_flail",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "legs-Pants_charcoal",
                "clothes-Robe_black",
                "hat-Hood_hood_black",
                "neck-Scarf_red",
                "cape-Tattered_black",
                "shoes-Boots_black",
                "weapon-Scythe_scythe",
            ],
        ],
    },
    "tinker": {
        "body": "female",
        "facing": "right",
        "attack": "shoot",
        "tiers": [
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Shoulderl_sandy",
                "legs-Pants_brown",
                "clothes-Sleeveless_bluegray",
                "shoes-Boots_brown",
                "weapon-Crossbow_crossbow",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "hair-Shoulderl_sandy",
                "legs-Pants_charcoal",
                "clothes-Longsleeve_charcoal",
                "armour-Leather_leather",
                "hat-Tricorne_brown",
                "shoes-Boots_charcoal",
                "weapon-Crossbow_crossbow",
            ],
            [
                "body-Body_color_light",
                "head-Human_female_light",
                "legs-Pants_charcoal",
                "clothes-Longsleeve_black",
                "armour-Leather_black",
                "shoulders-Leather_leather",
                "hat-Tricorne_black",
                "cape-Solid_bluegray",
                "shoes-Boots_black",
                "weapon-Crossbow_crossbow",
            ],
        ],
    },
}

ENEMIES = {
    # cellars
    "rat": {
        "body": "child",
        "facing": "left",
        "attack": "slash",
        "parts": ["body-Body_color_fur_grey", "head-Rat_fur_grey"],
    },
    "goblin": {
        "body": "child",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_pale_green",
            "head-Goblin_pale_green",
            "legs-Pants_brown",
            "clothes-Shortsleeve_brown",
            "weapon-Dagger_dagger",
        ],
    },
    "cutthroat": {
        "body": "male",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_light",
            "head-Human_male_gaunt_light",
            "legs-Pants_charcoal",
            "clothes-Longsleeve_charcoal",
            "shoes-Boots_black",
            "hat-Hood_charcoal",
            "weapon-Dagger_dagger",
        ],
    },
    "ambusher": {
        "body": "male",
        "facing": "left",
        "attack": "shoot",
        "parts": [
            "body-Body_color_light",
            "head-Human_male_light",
            "legs-Pants_forest",
            "clothes-Longsleeve_forest",
            "shoes-Boots_brown",
            "hat-Hood_forest",
            "quiver-Quiver_quiver",
            "weapon-Normal_light",
            "ammo-Ammo_arrow",
        ],
    },
    # catacombs
    "skeleton_archer": {
        "body": "male",
        "facing": "left",
        "attack": "shoot",
        "parts": [
            "body-Skeleton_skeleton",
            "head-Skeleton_skeleton",
            "quiver-Quiver_quiver",
            "weapon-Normal_dark",
            "ammo-Ammo_arrow",
        ],
    },
    "stitched": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_zombie_green",
            "head-Frankenstein_zombie_green",
            "legs-Pants_charcoal",
            "weapon-Club_club",
        ],
    },
    "skeleton": {
        "body": "male",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Skeleton_skeleton",
            "head-Skeleton_skeleton",
            "weapon-Arming_Sword_iron",
        ],
    },
    "revenant": {
        "body": "male",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Zombie_zombie",
            "head-Human_male_zombie_green",
            "legs-Pants_charcoal",
            "clothes-Longsleeve_brown",
        ],
    },
    "gravewarden": {
        "body": "male",
        "facing": "left",
        "attack": "thrust",
        "parts": [
            "body-Skeleton_skeleton",
            "head-Skeleton_skeleton",
            "armour-Plate_iron",
            "arms-Armour_iron",
            "shoulders-Plate_iron",
            "legs-Armour_iron",
            "hat-Close_helm_iron",
            "weapon-Spear_dark",
        ],
    },
    # warrens
    "orc": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_green",
            "head-Orc_male_green",
            "legs-Pants_brown",
            "bauldron-Bauldron_leather",
            "weapon-Waraxe_waraxe",
        ],
    },
    "boarman": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_fur_brown",
            "head-Boarman_fur_brown",
            "legs-Pants_brown",
            "weapon-Club_club",
        ],
    },
    "wolfman": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_fur_grey",
            "head-Wolf_male_fur_grey",
            "legs-Pants_brown",
        ],
    },
    "orc_spear": {
        "body": "muscular",
        "facing": "left",
        "attack": "thrust",
        "parts": [
            "body-Body_color_dark_green",
            "head-Orc_male_dark_green",
            "legs-Pants_charcoal",
            "bauldron-Bauldron_charcoal",
            "weapon-Spear_dark",
        ],
    },
    # crystal seam
    "hag": {
        "body": "female",
        "facing": "left",
        "attack": "cast",
        "parts": [
            "body-Body_color_pale_green",
            "head-Human_female_elderly_pale_green",
            "clothes-Robe_forest_green",
            "hat-Hood_forest",
            "weapon-Gnarled_staff_bronze",
        ],
    },
    "lizard": {
        "body": "male",
        "facing": "left",
        "attack": "thrust",
        "parts": [
            "body-Body_color_bright_green",
            "head-Lizard_male_bright_green",
            "legs-Pants_forest",
            "weapon-Spear_medium",
        ],
    },
    "troll": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_dark_green",
            "head-Troll_dark_green",
            "legs-Pants_brown",
            "weapon-Club_club",
        ],
    },
    "warlock": {
        "body": "male",
        "facing": "left",
        "attack": "cast",
        "parts": [
            "body-Body_color_pale_green",
            "head-Human_male_gaunt_pale_green",
            "clothes-Robe_purple",
            "hat-Hood_purple",
            "weapon-Gnarled_staff_gold",
        ],
    },
    # the maw
    "minotaur": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_fur_black",
            "head-Minotaur_fur_black",
            "legs-Pants_charcoal",
            "weapon-Waraxe_waraxe",
        ],
    },
    "vampire": {
        "body": "male",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_lavender",
            "head-Vampire_lavender",
            "legs-Pants_black",
            "clothes-Longsleeve_black",
            "cape-Solid_maroon",
            "shoes-Boots_black",
            "weapon-Rapier_rapier",
        ],
    },
    "wartotaur": {
        "body": "muscular",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Body_color_fur_copper",
            "head-Wartotaur_fur_copper",
            "legs-Pants_black",
            "shoulders-Plate_bronze",
            "weapon-Waraxe_waraxe",
        ],
    },
    "bone_knight": {
        "body": "male",
        "facing": "left",
        "attack": "slash",
        "parts": [
            "body-Skeleton_skeleton",
            "head-Skeleton_skeleton",
            "armour-Plate_gold",
            "arms-Armour_gold",
            "shoulders-Plate_gold",
            "legs-Armour_gold",
            "hat-Greathelm_gold",
            "cape-Solid_black",
            "shield-Heater_Shield_Base_coffee",
            "weapon-Longsword_longsword",
        ],
    },
}
